export const locationOptions = [
	{ value: 'Thanh Hóa (THD)', label: 'Thanh Hóa (THD)' },
	{ value: 'Vinh (VII)', label: 'Vinh (VII)' },
	{ value: 'Đà Nẵng (DAD)', label: 'Đà Nẵng (DAD)' },
	{ value: 'Huế (HUI)', label: 'Huế (HUI)' },
	{ value: 'Đồng Hới (VDH)', label: 'Đồng Hới (VDH)' },
	{ value: 'Tuy Hòa (TBB)', label: 'Tuy Hòa (TBB)' },
	{ value: 'Chu Lai (VCL)', label: 'Chu Lai (VCL)' },
	{ value: 'Pleiku (PXU)', label: 'Pleiku (PXU)' },
	{ value: 'Quy Nhơn (UIH)', label: 'Quy Nhơn (UIH)' },
	{ value: 'Hồ Chí Minh (SGN)', label: 'Hồ Chí Minh (SGN)' },
	{ value: 'Nha Trang (CXR)', label: 'Nha Trang (CXR)' },
	{ value: 'Đà Lạt (DLI)', label: 'Đà Lạt (DLI)' },
	{ value: 'Buôn Mê Thuộc (BMTV)', label: 'Buôn Mê Thuộc (BMTV)' },
	{ value: 'Phú Quốc (PQC)', label: 'Phú Quốc (PQC)' },
	{ value: 'Cần Thơ (VCA)', label: 'Cần Thơ (VCA)' },
	{ value: 'Côn Đảo (VCS)', label: 'Côn Đảo (VCS)' },
	{ value: 'Rạch Giá (VKG)', label: 'Rạch Giá (VKG)' },
	{ value: 'Cà Mau (CAH)', label: 'Cà Mau (CAH)' },
]
